name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11' ]
      fail-fast: false
    name: JAVA ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: gradle build --stacktrace
      - name: Upload Test Results and Reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: dogecoinj-core-test-results-jdk${{ matrix.java }}-${{ matrix.os }}
          path: |
            core/build/reports/tests/test/
            core/build/test-results/test/
